SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO




ALTER procedure [dbo].[sp_ajusta_OP] 
	@FILIAL VARCHAR(3), 
	@OP VARCHAR(11), 
	@PRODUTO VARCHAR(15), 
	@DESCPROD VARCHAR(40), 
	@CODANT VARCHAR(15), 
	@COMPONENTE VARCHAR(15), 
	@DESCCOMP VARCHAR(40), 
	@TIPO VARCHAR(1), 
	@SITUACA VARCHAR(1), 
	@UNIDADE VARCHAR(2), 
	@QTDEPCF FLOAT,
	@QTDEINF FLOAT
AS
--sp_ajusta_OP '101', '00312801001', 'PAN00095', 'PERLITE FA 2000 BIG BAG 210KG', '', 'GGF3010201', 'PALLET PBR MADEIRA NOVO DUPLA FACE 1,00X1,20', 'M', 'C', 'H', 10, 16.666666666666668
--EXEC    sp_ajusta_OP   '101',   '00275101001',   'PAN00090',   'undefined',   'PA001432',   'GAS311202',   'GAS EXPANSAO - CG',   'E',   'C',   'M3',   86.176,   0

/*
CODANT: ""
COMPONENTE: "GGF3010201"
DESCCOMP: "GASTOS GERAIS MOAGEM - CG"
DESCPROD: "PERLITE FA 8000 SACO 16KG"
FILIAL: "101"
OP: "00314701001"
PRODUTO: "PAN00099"
QTDEINF: 2.25
QTDEPCF: 10
SITUACA: "C"
TIPO: "M"
UNIDADE: "H"
*/
--SELECT * FROM PCP..OP WHERE OP = '00236901001'

declare 
	@QTDE int, 
	@QTDECAL FLOAT,
	@ESTRUTURA INT

SET @QTDE = (SELECT COUNT(*) FROM PCP..OP WHERE FILIAL = @FILIAL AND OP = @OP AND PRODUTO = @PRODUTO AND COMPONENTE = @COMPONENTE)
SET @ESTRUTURA = (SELECT COUNT(*) FROM HOMOLOGACAO..SG1010 WHERE G1_FILIAL = @FILIAL AND G1_COD = @PRODUTO AND G1_COMP = @COMPONENTE)

--sp_ajusta_OP FILIAL, OP, PA, DESCPA, CODANT, COMP, DESCCOMP, TIPO, SITUAÇÃO, UNIDADE, QYDEPCF, QTDEINF
--sp_ajusta_OP '101', '00314701001', 'PAN00099', 'PERLITE FA 2000 BIG BAG 210KG', '', 'GGF3010201', 'PALLET PBR MADEIRA NOVO DUPLA FACE 1,00X1,20', 'M', 'C', 'H', 10, 2.25

IF @SITUACA NOT IN ('A', 'P')

	BEGIN
		IF @QTDEINF > 0
			BEGIN
				SET @QTDECAL = ROUND(@QTDEINF, 4)
			END
		IF @QTDEINF = 0 AND @TIPO <> 'M'
			BEGIN

				SET @QTDECAL = ROUND(ISNULL((
									SELECT 
										ROUND(G1_QUANT / ((100 - G1_PERDA) / 100) * (@QTDEPCF / CASE WHEN B1_QB = 0 THEN 1 ELSE B1_QB END), 4)
									FROM 
										HOMOLOGACAO..SG1010 A WITH (NOLOCK) INNER JOIN
										HOMOLOGACAO..SB1010 B WITH (NOLOCK) ON
										G1_COD = B1_COD
									WHERE
										1 = 1
										AND A.R_E_C_D_E_L_ = 0
										AND B.R_E_C_D_E_L_ = 0
										--AND G1_FILIAL = '101'
										--AND G1_COD = 'PAN00090'
										--AND G1_COMP = 'GAS311202'
										AND G1_FILIAL = @FILIAL
										AND G1_COD = @PRODUTO
										AND G1_COMP = @COMPONENTE
								), 0), 4)

				--SELECT * FROM PCP..OP 
			END

		IF @QTDEINF = 0 AND @TIPO = 'M'
			BEGIN

				SET @QTDECAL = ROUND(ISNULL((
									SELECT 
										ROUND(G1_QUANT * (@QTDEINF / CASE WHEN B1_QB = 0 THEN 1 ELSE B1_QB END), 4)
									FROM 
										HOMOLOGACAO..SG1010 A WITH (NOLOCK) INNER JOIN
										HOMOLOGACAO..SB1010 B WITH (NOLOCK) ON
										G1_COD = B1_COD
									WHERE
										1 = 1
										AND A.R_E_C_D_E_L_ = 0
										AND B.R_E_C_D_E_L_ = 0
										--AND G1_FILIAL = '101'
										--AND G1_COD = 'PAN00090'
										--AND G1_COMP = 'GAS311202'
										AND G1_FILIAL = @FILIAL
										AND G1_COD = @PRODUTO
										AND G1_COMP = @COMPONENTE
								), 0), 4)

				--SELECT * FROM PCP..OP 
			END


		--QUANDO TEM O PRODUTO NO EMPENHO
		IF @QTDE = 1
			BEGIN
				UPDATE 
					PCP..OP
				SET
					QTDECAL = round(@QTDECAL, 4),
					SITUACA = CASE WHEN @SITUACA = 'K' THEN 'C' ELSE @SITUACA END
				WHERE 
					1 = 1
					AND FILIAL = @FILIAL 
					AND OP = @OP
					AND PRODUTO = @PRODUTO 
					AND COMPONENTE = @COMPONENTE
					AND TIPO <> CASE WHEN @SITUACA = 'K' THEN 'K' ELSE 'C' END
			END
		--QUANDO NÃO TEM O PRODUTO NO EMPENHO
		IF @QTDE = 0
			BEGIN
				IF @COMPONENTE = 'GGF3010201' AND @ESTRUTURA = 0
					BEGIN
						SET @ESTRUTURA = 0
					END
				ELSE
					BEGIN
						INSERT INTO PCP..OP 
							(FILIAL, OP, PRODUTO, DESCRICAO, CODANT, COMPONENTE, DESCRIC, ARMAZEM, QTDEPCF, QTDECAL, UNIDADE, TIPO, SITUACA, QTDE, QTDEORI, SALDO, ENTREGUE, ROTEIRO, OPERACAO, EMISSAO, FINAL )
						VALUES
							(@FILIAL, @OP, @PRODUTO, @DESCPROD, @CODANT, @COMPONENTE, @DESCCOMP, '01', ROUND(@QTDEPCF, 4), ROUND(@QTDEINF, 4), @UNIDADE, @TIPO, @SITUACA, 0, 0, 0, '', '01', '', '', '')
					END
			END
	END

IF @SITUACA = 'A'
	BEGIN
		UPDATE
			PCP..OP
		SET
			SITUACA = @SITUACA
		WHERE 
			1 = 1
			AND FILIAL = @FILIAL 
			AND OP = @OP
	END	

IF @SITUACA = 'V'
	BEGIN
		UPDATE
			PCP..OP
		SET
			SITUACA = @SITUACA
		WHERE 
			1 = 1
			AND FILIAL = @FILIAL 
			AND OP = @OP
	END	

IF @SITUACA = 'P'
	BEGIN
		UPDATE
			PCP..OP
		SET
			SITUACA = @SITUACA
		WHERE 
			1 = 1
			AND FILIAL = @FILIAL 
			AND OP = @OP
	END	
GO
