SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[View_Portal_OP_Config] as


SELECT 
	RTRIM(C2_FILIAL) FILIAL, 
	RTRIM(C2_NUM)+RTRIM(C2_ITEM)+RTRIM(C2_SEQUEN) OP, 
	CONVERT(VARCHAR(10), CAST(C2_EMISSAO AS DATETIME), 103) EMISSAO, 
	CASE 
		WHEN C2_DATRF = '' 
		THEN '' 
		ELSE CONVERT(VARCHAR(10), CAST(C2_DATRF AS DATETIME), 103) 
	END FINAL, 
	C2_QUANT QTDE, 
	C2_QUJE ENTREGUE, 
	RTRIM(B.B1_COD) PRODUTO, 
	RTRIM(B.B1_CODANT) CODANT,
	RTRIM(B.B1_DESC) DESCRICAO, 
	RTRIM(D4_LOCAL) ARMAZEM, 
	RTRIM(D4_COD) COMPONENTE, 
	RTRIM(D.B1_DESC) DESCRIC, 
	D4_QTDEORI QTDEORI, 
	0 QTDEPCF, 
	0 QTDECAL, 
	0 SALDO, 
	RTRIM(D4_ROTEIRO) ROTEIRO, 
	RTRIM(D4_OPERAC) OPERACAO, 
	RTRIM(D.B1_UM) UNIDADE,
	'E' TIPO,
	'W' SITUACA
	--INTO PCP..OP
	--TRUNCATE TABLE PCP..OP
	--DROP TABLE PCP..OP
FROM 
	HOMOLOGACAO..SC2010 A WITH (NOLOCK) INNER JOIN
	HOMOLOGACAO..SB1010 B WITH (NOLOCK) ON
	C2_PRODUTO = B.B1_COD INNER JOIN
	HOMOLOGACAO..SD4010 C WITH (NOLOCK) ON
	C2_NUM+C2_ITEM+C2_SEQUEN = D4_OP AND
	C2_FILIAL = D4_FILIAL INNER JOIN
	HOMOLOGACAO..SB1010 D WITH (NOLOCK) ON
	D4_COD = D.B1_COD
WHERE
	1 = 1
	AND A.R_E_C_D_E_L_ = 0
	AND B.R_E_C_D_E_L_ = 0
	AND C.R_E_C_D_E_L_ = 0
	AND D.R_E_C_D_E_L_ = 0
GO
